CREATE TABLE games (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pgn TEXT NOT NULL,
    initial_fen TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE moves (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id BIGINT NOT NULL REFERENCES games(id),
    ply INTEGER NOT NULL CHECK (ply > 0),
    uci VARCHAR(5) NOT NULL,
    fen TEXT NOT NULL,
    CONSTRAINT uq_moves_game_ply UNIQUE (game_id, ply)
);

CREATE TABLE analysis_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id BIGINT NOT NULL REFERENCES games(id),
    depth INTEGER NOT NULL,
    status VARCHAR(16) NOT NULL CHECK (status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    started_at TIMESTAMP WITH TIME ZONE,
    finished_at TIMESTAMP WITH TIME ZONE,
    error_message TEXT,
    initial_best_mov TEXT,
    initial_evaluation DOUBLE PRECISION,
    initial_variation TEXT
);

CREATE INDEX idx_analysis_jobs_game ON analysis_jobs(game_id);

CREATE TABLE move_analyses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    move_id BIGINT NOT NULL REFERENCES moves(id),
    job_id BIGINT NOT NULL REFERENCES analysis_jobs(id),
    best_mov TEXT NOT NULL,
    evaluation DOUBLE PRECISION NOT NULL,
    variation TEXT NOT NULL,
    CONSTRAINT uq_move_analyses_job_move UNIQUE (job_id, move_id)
);

CREATE INDEX idx_move_analyses_move ON move_analyses(move_id);
